name: cpf_util
description: A Dart package to generate, validate and format Brazilian's CPF in an easy way
version: 1.0.3
# author: Pedro Lemos <lemozxpedro@gmail.com>
homepage: https://github.com/pedrolemoz/cpf_util

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies: null
dev_dependencies:
  effective_dart: ^1.2.0
  test: ^1.15.4
